# Generated by Django 2.2.3 on 2019-07-13 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_latlong', models.CharField(blank=True, default='NotAvailable', max_length=100, verbose_name='Coordinates')),
                ('req_description', models.CharField(default='NotAvailable', max_length=500, verbose_name='Description')),
                ('uid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
