# Generated by Django 2.2.3 on 2019-07-13 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='uid',
        ),
        migrations.AddField(
            model_name='request',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
