# Generated by Django 2.2.3 on 2019-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190713_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='loc_latlong_accurate',
            field=models.CharField(blank=True, default='NotAvailable', max_length=100, verbose_name='Coordinates Accurate'),
        ),
    ]
