# Generated by Django 2.2.3 on 2019-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_request_loc_latlong_accurate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='loc_latlong',
            field=models.CharField(max_length=100, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='request',
            name='loc_latlong_accurate',
            field=models.CharField(blank=True, max_length=100, verbose_name='Coordinates Accurate'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
