# Generated by Django 2.2.3 on 2019-07-14 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190714_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='phoneno',
            field=models.CharField(default=123456789, max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
