# Generated by Django 2.2.3 on 2019-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_request_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
