# Generated by Django 2.2.3 on 2019-07-15 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190714_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
