# Generated by Django 2.2.3 on 2019-07-16 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20190715_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('l0', 'level-1-SuperAdmin'), ('l2', 'level-2-Manager '), ('l3', 'level-3-Volunteers'), ('l4', 'level-4-Normal Users')], default='l4', max_length=15, verbose_name='Type of User')),
                ('phoneno', models.CharField(error_messages={'invalid': 'Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>'}, max_length=14, validators=[django.core.validators.RegexValidator(regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')], verbose_name='Phone Number')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('s1', 'Case Resolved'), ('s2', 'Case Assigned to a volunteer '), ('s3', 'Case under process'), ('s4', 'Case Open')], default='s4', max_length=15, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phoneno',
            field=models.CharField(error_messages={'invalid': 'Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>'}, max_length=14, validators=[django.core.validators.RegexValidator(regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
